-- Generated by scripts/hypr2lua.
-- Source: /home/oldjobobo/Projects/themes/omarchy-waffle-cat-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgba(c87d2af5)", "rgba(fffaf0f5)" },
  angle = 45,
}
local inactiveBorderColor = "rgba(6b5650f5)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 2,
    gaps_in = 7,
    gaps_out = 14,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    rounding = 14,
    rounding_power = 2,
    blur = {
      enabled = true,
      size = 5,
      passes = 2,
    },
    shadow = {
      enabled = true,
      range = 14,
      render_power = 3,
      color = "rgba(33282db5)",
      color_inactive = "rgba(292025d8)",
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("waffleSmooth", { type = "bezier", points = { { 0.24, 0.9 }, { 0.2, 1.0 } } })
hl.curve("waffleSettle", { type = "bezier", points = { { 0.2, 1.0 }, { 0.3, 1.0 } } })
hl.curve("waffleFade", { type = "bezier", points = { { 0.18, 0.0 }, { 0.12, 1.0 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 5,
  bezier = "waffleSmooth",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 5,
  bezier = "waffleSettle",
  style = "popin 8%",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 4,
  bezier = "waffleFade",
  style = "popin 82%",
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 5,
  bezier = "waffleSmooth",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 6,
  bezier = "waffleFade",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 5,
  bezier = "waffleFade",
})
hl.animation({
  leaf = "layers",
  enabled = true,
  speed = 5,
  bezier = "waffleSettle",
  style = "slidefade",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 5,
  bezier = "waffleSettle",
  style = "slidefade",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 4,
  bezier = "waffleFade",
  style = "fade",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 4,
  bezier = "waffleSmooth",
  style = "slidefade",
})
